FROM docker.io/zmkfirmware/zmk-build-arm:stable

# Define the default username and home directory as overrideable arguments
ARG SHELL_USER=developer
ARG SHELL_UID=1000
ARG SHELL_GID=1000
ENV HOME=/home/${SHELL_USER}
ENV USER=${SHELL_USER}
RUN export uid=${SHELL_UID} gid=${SHELL_GID} && \
    mkdir -p /home/${SHELL_USER} && \
    echo "${SHELL_USER}:x:${uid}:${gid}:${SHELL_USER},,,:${HOME}:/bin/bash" >> /etc/passwd && \
    echo "${SHELL_USER}:x:${uid}:" >> /etc/group && \
    chown ${uid}:${gid} -R ${HOME}
RUN echo ${SHELL_USER}:dummy | chpasswd

USER "${USER}"

WORKDIR /app

COPY config/west.yml config/west.yml

# West Init
RUN west init -l config
# West Update
RUN west update
# West Zephyr export
RUN west zephyr-export

COPY bin/build.sh ./

CMD ["./build.sh"]

# vim:et ts=4 sts=4 sw=4 filetype=dockerfile
